apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
  name: deep-ployment-operator.v0.0.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions: {}
  description: Operator for Deeptalk
  displayName: DeepPloyment Operator
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - deeptalk
  - deepshore
  - techtalk
  links:
  - name: Deep Ployment Operator
    url: https://deep-ployment-operator.domain
  maturity: alpha
  provider:
    name: grothesk
    url: deepshore.de
  version: 0.0.0
