# permissions for end users to edit deepployments.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: deepployment-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: deep-ployment-operator
    app.kubernetes.io/part-of: deep-ployment-operator
    app.kubernetes.io/managed-by: kustomize
  name: deepployment-editor-role
rules:
- apiGroups:
  - deeptalk.deepshore.de
  resources:
  - deepployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - deeptalk.deepshore.de
  resources:
  - deepployments/status
  verbs:
  - get
