apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: deep-ployment-catalog
  namespace: deep-ployment-operator
spec:
  sourceType: grpc
  image: quay.io/maltegroth/deep-ployment-catalog:latest
  displayName: DeepPloyment Catalog
  publisher: Deeptalk
  updateStrategy:
    registryPoll:
      interval: 10m